version: "3.7"
services:
  webserver:
    container_name: webserver
    build: ./web
    ports:
      - 8080:80
    volumes:
      - ./web/src/:/var/www/html/
      - /var/run/docker.sock:/custom/docker/docker.sock
    command:
      [
        "sh",
        "-c",
        "chown root:docker /custom/docker/docker.sock && apache2-foreground",
      ]
    privileged: true
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: idor
      MYSQL_USER: web
      MYSQL_PASSWORD: web@server123
  mysql:
    container_name: mysql
    image: mysql:latest
    hostname: mysql
    ports:
      - 3306:3306
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: Checkpass@123123
      MYSQL_DATABASE: idor
      MYSQL_USER: web
      MYSQL_PASSWORD: web@server123
